use_frameworks!

platform :ios, '12.0'

target 'BaseTableViewKit_Example' do
  pod 'BaseTableViewKit', :path => '../'
  pod 'DifferenceKit'
  target 'BaseTableViewKit_Tests' do
    inherit! :search_paths

    
  end
end
